# Travis CI build file for CircuitBreaker.
# CircuitBreaker runs on OS X and Linux (Ubuntu).

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop
    - /^issue.*$/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=swift-4.2
    - os: osx
      osx_image: xcode9.4
      sudo: required
      env: SWIFT_SNAPSHOT=swift-4.1.2 JAZZY_ELIGIBLE=true
    - os: osx
      osx_image: xcode10
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
