# docker-compose up
app:
  image: ibmcom/swift-ubuntu:4.0.2
  volumes:
    - .:/CircuitBreaker
  command: bash -c "cd /CircuitBreaker && swift package clean && swift build && swift test && swift package clean"
